[package]
name = "rottenes"
version = "0.1.0"
authors = ["CatWithSailorHat <catwithsailorhat@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
sdl2 = "0.34.0"