[package]
name = "rottenes-sdl2"
version = "0.1.0"
authors = ["CatWithSailorHat <catwithsailorhat@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
nes = { path = "../nes" }
